### ISSUE TITLE
Change default directory

### ISSUE THREAD

**Issue by denniszollo** [swift-nav/gnss-analysis#43]
https://github.com/swift-nav/gnss-analysis/blob/1a6c6b000ffdc1545b9725ee2f024099661b2c66/gnss_analysis/tables.py#L562

how about somwhere like /tmp that is guaranteed to exist?

**Comment by mookerji** [comment]
It's really not uncommon to have a canonical directory where things like are put. You can just create `/swift/` in your root and chown it for your user. Alternatively, we could make it `~/.swift/`or something. 

It was originally /tmp, but you'll find that this directly gets cleared out periodically (and on reboots).

**Comment by fnoble** [comment]
Consider using the `tempfile` module from the standard library to get a portable temp directory.

https://docs.python.org/2/library/tempfile.html

Agree that expecting people to create `/swift` is a bit janky. `~/.swift` would be much better but still non portable.
